# Generated by Django 5.0.1 on 2025-01-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useracc', '0003_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
