# Generated by Django 5.0.1 on 2025-01-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useracc', '0005_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=True, max_length=225, unique=True ),
        ),
    ]