# Generated by Django 5.0.1 on 2025-05-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useracc", "0007_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal User"),
                    ("admin", "Administrator"),
                    ("theatre_owner", "Theatre Owner"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
