# Generated by Django 5.0.1 on 2025-05-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useracc", "0009_user_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_theatre_owner",
            field=models.BooleanField(default=False),
        ),
    ]
