services:
  web:
    image: mhdasjad/movie_ticket-web:1.0.2
    command: daphne -b 0.0.0.0 -p 8000 Backend.asgi:application
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./Backend:/app 
      - movie_ticket_static:/app/staticfiles
      - movie_ticket_media:/app/media
    networks:
      - backend-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend-network
  celery_worker:
    image: mhdasjad/movie_ticket-web:1.0.2
    command: celery -A Backend worker --loglevel=info
    volumes: 
      - ./Backend:/app 
      - movie_ticket_media:/app/media

    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - backend-network
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asjadk123
      POSTGRES_DB: movie_ticket
    volumes:
      - db_data_local:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  db_data_local:
  movie_ticket_static:
  movie_ticket_media:

networks:
  backend-network:
    driver: bridge