# Generated by Django 5.0.1 on 2025-01-21 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 21, 18, 19, 20, 665110)
            ),
        ),
    ]
