# Generated by Django 5.0.1 on 2025-01-23 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_movie_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 23, 14, 6, 15, 790421)
            ),
        ),
    ]
