# Generated by Django 5.0.1 on 2025-04-03 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_seatscreenlayout_screen'),
        ('theatres', '0003_alter_showtime_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screens', to='seats.seatscreenlayout'),
        ),
    ]
