# Generated by Django 5.0.1 on 2025-04-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "theatres",
            "0005_timeslot_remove_showtime_unique_show_per_screen_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="showtime",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
