# Generated by Django 5.0.1 on 2025-04-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatres", "0006_showtime_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
