# Generated by Django 5.0.1 on 2025-05-20 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatres', '0007_screen_is_approved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='showtime',
            name='old_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='theatres.timeslot'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showtime', to='theatres.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('screen', 'old_slot', 'show_date')},
        ),
    ]
