# Generated by Django 5.0.1 on 2025-05-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatres', '0008_alter_showtime_unique_together_showtime_old_slot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('screen', 'slot', 'show_date')},
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='old_slot',
        ),
        migrations.AddField(
            model_name='showtime',
            name='old_slot',
            field=models.ManyToManyField(blank=True, null=True, related_name='showtimes', to='theatres.timeslot'),
        ),
    ]
