# Generated by Django 5.0.1 on 2025-05-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "theatres",
            "0008_alter_showtime_unique_together_alter_showtime_movie_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="showtime",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="showtime",
            name="slot",
        ),
    ]
