# Generated by Django 5.0.1 on 2025-05-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatres', '0009_alter_showtime_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('screen', 'show_date')},
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='old_slot',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='slot',
        ),
        migrations.AddField(
            model_name='showtime',
            name='slot',
            field=models.ManyToManyField(blank=True, related_name='showtimes', to='theatres.timeslot'),
        ),
    ]
