# Generated by Django 5.0.1 on 2025-05-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatres", "0009_alter_showtime_unique_together_remove_showtime_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="theatre",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="theatre",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
