# Generated by Django 5.0.1 on 2025-06-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatres", "0010_theatre_latitude_theatre_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
