# Generated by Django 5.0.1 on 2025-05-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movie_cities'),
        ('theatres', '0011_alter_showtime_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.UniqueConstraint(fields=('screen', 'slot', 'show_date'), name='unique_showtime_per_slot'),
        ),
    ]
