# Generated by Django 5.0.1 on 2025-05-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movie_cities'),
        ('theatres', '0012_showtime_unique_showtime_per_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='showslots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='showtime',
            name='unique_showtime_per_slot',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='slot',
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TimeSlotSlot', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='showslots',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatres.showtime'),
        ),
        migrations.AddField(
            model_name='showslots',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatres.timeslot'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='slots',
            field=models.ManyToManyField(blank=True, through='theatres.showslots', to='theatres.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='showslots',
            unique_together={('showtime', 'slot')},
        ),
    ]
