# Generated by Django 5.2 on 2025-07-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatres", "0012_remove_timeslot_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
