# Generated by Django 5.2 on 2025-07-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatres", "0013_screen_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
