# Generated by Django 5.0.1 on 2025-03-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_owner', '0004_remove_theaterownerprofile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theaterownerprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='theaterownerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
