# Generated by Django 5.0.1 on 2025-04-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_owner', '0008_alter_theaterownerprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theaterownerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='theaterownerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=22, null=True),
        ),
    ]
