# Generated by Django 5.2 on 2025-07-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre_owner", "0010_theaterownerprofile_avatar_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theaterownerprofile",
            name="avatar_config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="theaterownerprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
