# Generated by Django 5.0.1 on 2025-04-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0005_seats_is_seat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seats',
            unique_together=set(),
        ),
    ]
