# Generated by Django 5.0.1 on 2025-05-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='show',
        ),
    ]
