# Generated by Django 5.0.1 on 2025-04-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
    ]
