# Generated by Django 5.0.1 on 2025-05-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_cancelled_at_booking_refund_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='capture_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
