# Generated by Django 5.0.1 on 2025-05-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaints",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
    ]
