# Generated by Django 5.0.1 on 2025-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_complaints_is_resolved"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaints",
            name="response_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
