# Generated by Django 5.0.1 on 2025-06-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0005_complaints_response_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaints",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to="review.chatlog",
            ),
        ),
    ]
